version: '2'
services:
  control:
    image: mav_control
    command: roslaunch mav_control demo.launch rigid_body:=bebop
    volumes:
      - ./logs:/home/root/.ros/log:rw
    network_mode: host
    env_file:
      - ./ros.demo.env
  monitor:
    image: docker_ui
    command: roslaunch docker_ui monitor.launch video:=true video_stream:=/bebop/image_raw
    volumes:
      - ./logs:/root/.ros/log:rw
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    env_file:
      - ./ros.demo.env
    environment:
      - "ifaces=['eno1']"
