-
   key: KEY_0
   commands:
      - waypoint:
         frame_id: World
         point: [0, 0, 1.5]
         tol: 0.5
-
   key: KEY_1
   commands:
      - waypoint:
         frame_id: World
         point: [2, 2, 1]
         tol: 0.5
      - sleep:
         duration: 2
      - waypoint:
         frame_id: World
         point: [2, -2, 1]
         tol: 0.5
      - sleep:
         duration: 2
      - waypoint:
         frame_id: World
         point: [-2, -2, 1]
         tol: 0.5
      - sleep:
         duration: 2
      - waypoint:
         frame_id: World
         point: [-2, 2, 1]
         tol: 0.5
      - sleep:
         duration: 2
      - waypoint:
         frame_id: World
         point: [2, 2]
         tol: 0.5
-
   key: KEY_3
   commands:
      - path:
         frame_id: World
         curve: [[-2, -2], [-2, 2], [2, 2], [2, -2], [-2, -2]]
         tol: 0.5
         altitude: 1
-
   key: KEY_z
   commands:
      - loop:
         name: 'eight'
         alpha: 0.6
         frame_id: World
         center: [0, 0, 1]
         radius: 1.6
-
   key: KEY_x
   commands:
      - loop:
         name: 'f1'
         frame_id: World
         center: [0, 0, 1]
         radius: 2
-
   key: KEY_c
   commands:
      - loop:
         name: 'circle'
         frame_id: World
         center: [0, 0, 1]
         radius: 2
